version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env:
      QDRANT_HOST: localhost
      QDRANT_PORT: 6333
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
